### ISSUE TITLE
got 'round@@GLIBC_2.2.5' error when compling with BUILD_SHARED_LIBS=ON

### ISSUE THREAD

**Issue by golfbears** [erikd/libsndfile#489]
Hi:
After I cmake with BUILD_SHARED_LIBS=ON, cmake .. -DBUILD_SHARED_LIBS=ON,
then I get an error:/usr/bin/ld: CMakeFiles/sndfile-metadata-set.dir/programs/common.c.o: undefined reference to symbol 'round@@GLIBC_2.2.5', I worked in Ubuntu16.04 and cloned the version libsndfile-1.0.29pre2. 
Anyone ever met this problem? thanks and waiting the help!

**Comment by erikd** [comment]
Try doing `cmake clean` and retrying.
