### ISSUE TITLE
1.0.26 fails to compile on OSX/PPC

### ISSUE THREAD

**Issue by x42** [erikd/libsndfile#108]
since the update to 1.0.26 libsndfile fails to compile for PPC architecture (1.0.25 works)

```
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -DMAC_OS_X_VERSION_MAX_ALLOWED=1050 -mmacosx-version-min=10.5 -arch ppc -O3 -I/System/Library/Frameworks/Carbon.framework/Headers -std=gn
u99 -Wall -Wextra -Wdeclaration-after-statement -Wpointer-arith -funsigned-char -D_FORTIFY_SOURCE=2 -Wcast-align -Wcast-qual -Wbad-function-cast -Wwrite-strings -Wundef -Wuninitialized -Winit
-self -Wnested-externs -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -pipe -I/Developer/Headers/FlatCarbon -MT macbinary3.lo -MD -MP -MF .deps/macbinary3.Tpo -c macbinary3.c
  -fno-common -DPIC -o .libs/macbinary3.o
macbinary3.c:28:25: error: operator '>=' has no left operand
Makefile:858: recipe for target 'macbinary3.lo' failed
make[2]: *** [macbinary3.lo] Error 1
```

**Comment by x42** [comment]
Simply removing the #ifdef  in src/macbinary3.c fixes this. The two functions are identical anyway.
